### ISSUE TITLE
Not working on Anki 2.1.8-1 (Linux)

### ISSUE THREAD

**Issue by mpasa** [Arthur-Milchior/anki-better-database#1]
I'm getting this Stacktrace while trying to start Anki with the addon installed.

```
File "/usr/share/anki/aqt/addons.py", line 60, in loadAddons
    __import__(dir)
  File "/home/miguel/.local/share/Anki2/addons21/1585491271/__init__.py", line 1, in <module>
    from . import init
  File "/home/miguel/.local/share/Anki2/addons21/1585491271/init.py", line 1, in <module>
    from .tables.configurations import *
ModuleNotFoundError: No module named '1585491271.tables'
```

**Comment by Arthur-Milchior** [comment]
Code updated with every files. Sorry :s

**Comment by mpasa** [comment]
Now it starts correctly, but clicking on "Clarify the database" does nothing. Is it supposed to generate a file somewhere?

**Comment by Arthur-Milchior** [comment]
Yep. Well, I guess I should have thought about mentioning the file location in the documentation. The file is supposed to be in the add-on folder. At least that what happens when I run it on ubuntu. I can't make any promise for other OS

**Comment by mpasa** [comment]
Found it! I'm closing the issue and it's already working

**Comment by Arthur-Milchior** [comment]
Thank you a lot for the feedback
